# Generated by Django 4.1 on 2022-09-12 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_name_role_name1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='name1',
            new_name='name',
        ),
    ]
